### ISSUE TITLE
its work for TI 8.3.0 Alloy App ?

### ISSUE THREAD

**Issue by sourabhpatil365** [gnosticism/Titanium-Appcelerator-GeoFence-Module-iOS#3]
var ci_geofencing = require('ci.geofencing');   

var regions = [];  
regions.push({
	"title" : "Aurus ",
	"latitude" : 19.082996,
	"longitude" : 72.8401475,
	"radius" : 20
});

regions.push({
	"title" : "Malad Station",
	"latitude" : 19.1869676,
	"longitude" : 72.8467006,
	"radius" : 20
});

regions.push({
	"title" : "Andheri Station",
	"latitude" : 19.1205496,
	"longitude" :72.84557,
	"radius" : 20
});

ci_geofencing.startGeoFencing(regions, function(event) {
	Ti.API.info('info ' + JSON.stringify(event, null, 2));

	if ( event.type === "exited_region") {
		
		Ti.API.info('exited_region ' + JSON.stringify(event, null, 2));
		alert( 'exited_region ' + event.identifier);
		
		//ci_geofencing.stopGeoFencing();  
	}
	
	if ( event.type === "monitoring_region") {
		
		Ti.API.info('monitoring_region ' + JSON.stringify(event, null, 2));
		alert( 'monitoring_region ' + event.identifier);
		
		ci_geofencing.stopGeoFencing();
	}
	
	 if (event.type == "entered_region")
    {
    	Ti.API.info('entered_region ' + JSON.stringify(event, null, 2));
    	
    			alert( 'entered_region ' + event.identifier);

	
    }
    
    
	
	  
	
});

**Comment by sourabhpatil365** [comment]
its only show monitoring_region alert
Event exited_region and entered_region it is not fired 
AUTHORIZATION_ALWAYS permissions also given.
please give reply as early as possible 
i'm waiting for your valuable rply.......

**Comment by gurudey** [comment]
Hi make sure you're testing this on real device and use larger radius of around 200 & above. there are few other parameters you may have preset in your app that may be overriding the module values:
Ti.Geolocation.preferredProvider 
Titanium.Geolocation.accuracy
Titanium.Geolocation.distanceFilter
